 

// ******************************************************
// DO NOT CHANGE THE CONTENT OF THIS FILE
// This file was generated by the T4 engine and the 
// contents of this source code will be changed after
// the custom tool was run.
// ******************************************************
using System;
using System.Collections.Generic;
using System.ServiceModel;
using ByteartRetail.Application;
using ByteartRetail.DataObjects;
using ByteartRetail.ServiceContracts;
using ByteartRetail.Infrastructure;

namespace ByteartRetail.Services
{
	public class UserService : IUserService
	{
		private readonly IUserService userServiceImpl = ServiceLocator.Instance.GetService<IUserService>();
				public UserDataObjectList CreateUsers(UserDataObjectList userDataObjects)
		{
			try
			{
				return userServiceImpl.CreateUsers(userDataObjects);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public Boolean ValidateUser(String userName, String password)
		{
			try
			{
				return userServiceImpl.ValidateUser(userName, password);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public Boolean DisableUser(UserDataObject userDataObject)
		{
			try
			{
				return userServiceImpl.DisableUser(userDataObject);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public Boolean EnableUser(UserDataObject userDataObject)
		{
			try
			{
				return userServiceImpl.EnableUser(userDataObject);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public UserDataObjectList UpdateUsers(UserDataObjectList userDataObjects)
		{
			try
			{
				return userServiceImpl.UpdateUsers(userDataObjects);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public void DeleteUsers(UserDataObjectList userDataObjects)
		{
			try
			{
				 userServiceImpl.DeleteUsers(userDataObjects);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public UserDataObject GetUserByKey(Guid ID, QuerySpec spec)
		{
			try
			{
				return userServiceImpl.GetUserByKey(ID, spec);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public UserDataObject GetUserByEmail(String email, QuerySpec spec)
		{
			try
			{
				return userServiceImpl.GetUserByEmail(email, spec);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public UserDataObject GetUserByName(String userName, QuerySpec spec)
		{
			try
			{
				return userServiceImpl.GetUserByName(userName, spec);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public UserDataObjectList GetUsers(QuerySpec spec)
		{
			try
			{
				return userServiceImpl.GetUsers(spec);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public RoleDataObjectList GetRoles()
		{
			try
			{
				return userServiceImpl.GetRoles();
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public RoleDataObject GetRoleByKey(Guid id)
		{
			try
			{
				return userServiceImpl.GetRoleByKey(id);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public RoleDataObjectList CreateRoles(RoleDataObjectList roleDataObjects)
		{
			try
			{
				return userServiceImpl.CreateRoles(roleDataObjects);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public RoleDataObjectList UpdateRoles(RoleDataObjectList roleDataObjects)
		{
			try
			{
				return userServiceImpl.UpdateRoles(roleDataObjects);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public void DeleteRoles(IDList roleIDs)
		{
			try
			{
				 userServiceImpl.DeleteRoles(roleIDs);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public void AssignRole(Guid userID, Guid roleID)
		{
			try
			{
				 userServiceImpl.AssignRole(userID, roleID);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public void UnassignRole(Guid userID)
		{
			try
			{
				 userServiceImpl.UnassignRole(userID);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public RoleDataObject GetUserRoleByUserName(String userName)
		{
			try
			{
				return userServiceImpl.GetUserRoleByUserName(userName);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
	}
}


