 

// ******************************************************
// DO NOT CHANGE THE CONTENT OF THIS FILE
// This file was generated by the T4 engine and the 
// contents of this source code will be changed after
// the custom tool was run.
// ******************************************************
using System;
using System.Collections.Generic;
using System.ServiceModel;
using ByteartRetail.Application;
using ByteartRetail.DataObjects;
using ByteartRetail.ServiceContracts;
using ByteartRetail.Infrastructure;

namespace ByteartRetail.Services.SelfHosting
{
	[ServiceBehavior(InstanceContextMode = InstanceContextMode.PerSession)]
	public class OrderService : IOrderService
	{
		private readonly IOrderService orderServiceImpl = ServiceLocator.Instance.GetService<IOrderService>();
				public Int32 GetShoppingCartItemCount(Guid userID)
		{
			try
			{
				return orderServiceImpl.GetShoppingCartItemCount(userID);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public void AddProductToCart(Guid customerID, Guid productID, Int32 quantity)
		{
			try
			{
				 orderServiceImpl.AddProductToCart(customerID, productID, quantity);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public ShoppingCartDataObject GetShoppingCart(Guid customerID)
		{
			try
			{
				return orderServiceImpl.GetShoppingCart(customerID);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public void UpdateShoppingCartItem(Guid shoppingCartItemID, Int32 quantity)
		{
			try
			{
				 orderServiceImpl.UpdateShoppingCartItem(shoppingCartItemID, quantity);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public void DeleteShoppingCartItem(Guid shoppingCartItemID)
		{
			try
			{
				 orderServiceImpl.DeleteShoppingCartItem(shoppingCartItemID);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public SalesOrderDataObject Checkout(Guid customerID)
		{
			try
			{
				return orderServiceImpl.Checkout(customerID);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public void Confirm(Guid orderID)
		{
			try
			{
				 orderServiceImpl.Confirm(orderID);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public void Dispatch(Guid orderID)
		{
			try
			{
				 orderServiceImpl.Dispatch(orderID);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public SalesOrderDataObjectList GetSalesOrdersForUser(Guid userID)
		{
			try
			{
				return orderServiceImpl.GetSalesOrdersForUser(userID);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public SalesOrderDataObjectList GetAllSalesOrders()
		{
			try
			{
				return orderServiceImpl.GetAllSalesOrders();
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public SalesOrderDataObject GetSalesOrder(Guid orderID)
		{
			try
			{
				return orderServiceImpl.GetSalesOrder(orderID);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public void Dispose() { orderServiceImpl.Dispose(); }
	}
}